language: node_js
node_js:
 - "12.16.1"
deploy:
  - provider: elasticbeanstalk
    access_key_id: 
      secure: ${AWS_ACCESS_KEY_ID}
    secret_access_key: 
      secure: ${AWS_SECRET_ACCESS_KEY}
    region: "us-east-2"
    app: "ClubAgile-backend"                     
    env: "ClubagileBackend-env"                     
    bucket_name: ${AWS_S3_BUCKET}
    on:
      branch: "dev"

after_deploy:
  - echo "Application Deployed!"